import type { CapacitorConfig } from "@capacitor/cli";

const config: CapacitorConfig = {
  /*
    This becomes the native iOS bundle identifier.

    Do not casually change it after installing the app,
    because iOS will consider a different identifier to
    be a different application.
  */
  appId: "com.arnavsingh.mealplanner",

  /*
    This is the name shown underneath the app icon.
  */
  appName: "Meal Planner",

  /*
    This must match the directory generated by the
    Next.js static export.
  */
  webDir: "out",
};

export default config;